spring.application.name=sitepulse-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sitepulse}
spring.datasource.username=${DB_USERNAME:sitepulse_user}
spring.datasource.password=${DB_PASSWORD:sitepulse_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized