CREATE TABLE clients
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150)              NOT NULL,
    contact_email VARCHAR(254),
    contact_phone VARCHAR(30),
    status        VARCHAR(30)               NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE  NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE  NOT NULL,

    CONSTRAINT uk_clients_name UNIQUE (name),

    CONSTRAINT chk_clients_name_not_blank
        CHECK (LENGTH(TRIM(name)) > 0),

    CONSTRAINT chk_clients_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE INDEX idx_clients_status
    ON clients (status);